person:
    age: 20
    name: 小红
server:
    port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hf_jpa?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true
  redis:
    database: 1
  mail:
    host: smtp.qq.com
    username: 787315249@qq.com
    password: egcujdezubfubebi

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.wzszy.domain

#  egcujdezubfubebi